name: Build and Publish

on:
  push:
    branches:
      - PoC  # Define the branch to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@3
        with:
          dotnet-version: 7.0.x  # Specify the .NET version you need

      - name: Restore dependencies
        run: dotnet restore

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/src/TrackYourDay.MAUI/obj/project.assets.json'  # Adjust the path to your project's dependency files
          key: dependencies-${{ hashFiles('**/obj/project.assets.json') }}
          restore-keys: |
            dependencies-

      - name: Build and Test
        run: dotnet build --configuration Release --no-restore
        # Add additional test steps here if needed
